x-postgres_env: &postgres_env
  POSTGRES_DB: docmost
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: $APP_URL
      APP_SECRET: $APP_SECRET
      DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - $DOCMOST_STORAGE_PATH:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      <<: *postgres_env
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  dbbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
        - $DB_BACKUP_PATH:/backups
    links:
        - db
    depends_on:
        - db
    environment:
        <<: *postgres_env
        POSTGRES_HOST: db
        POSTGRES_EXTRA_OPTS: "-Z1 --schema=public --blobs"
        SCHEDULE: "@hourly"
        BACKUP_ON_START: TRUE
        BACKUP_KEEP_DAYS: 7
        BACKUP_KEEP_WEEKS: 4
        BACKUP_KEEP_MONTHS: 6
        HEALTHCHECK_PORT: 8080

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: