x-shared-env: &shared-env
  PUID: 1000
  PGID: 1000
  TZ: ${TZ:-America/Chicago}

services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE:-nextcloud:latest}
    container_name: nextcloud
    restart: unless-stopped
    networks: 
      - nextcloud
    depends_on:
      - mariadb
      - redis
    ports:
      - ${NEXTCLOUD_PORT:-8081}:80
    volumes:
      - ${APPDATA_DIR}/html:/var/www/html
      - ${APPDATA_DIR}/custom_apps:/var/www/html/custom_apps
      - ${APPDATA_DIR}/config:/var/www/html/config
      - ${DATA_DIR}/data:/var/www/html/data
    environment:
      <<: *shared-env
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpassword}
      MYSQL_HOST: mariadb
      REDIS_HOST: redis

  mariadb:
    image: mariadb:11.8
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      - nextcloud
    volumes:
      - nextcloud_mariadb:/var/lib/mysql
    environment:
      <<: *shared-env
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    networks: 
      - nextcloud
    ports:
      - 9981:9980
    environment:
      <<: *shared-env
      password: password
      username: nextcloud
      domain: ${COLLABORA_DOMAIN:-example.com}
      extra_params: --o:ssl.enable=true

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - nextcloud_redis:/data  
    networks: 
      - nextcloud

  dbbackups:
    image: tiredofit/db-backup:latest
    restart: always
    depends_on:
      - mariadb
    networks: 
      - nextcloud
    volumes:
      - ${APPDATA_DIR}/mariadb-backups:/backup
    environment:
      # --- Global/job defaults ---
      DEFAULT_BACKUP_BEGIN: "0 * * * *"     # run at minute 0 every hour (cron)
      DEFAULT_BACKUP_LOCATION: "FILESYSTEM"
      DEFAULT_COMPRESSION: "GZ"             # gz, bz, xz, zstd, none
      DEFAULT_CLEANUP_TIME: "10080"         # minutes to keep; 7 days = 7*24*60
      # --- Job 1: MariaDB/MySQL connection/options ---
      DB01_TYPE: mysql
      DB01_HOST: mariadb
      DB01_PORT: "3306"
      DB01_NAME: "${MYSQL_DATABASE}"        # or "ALL" to dump everything
      DB01_USER: "${MYSQL_USER}"
      DB01_PASS: "${MYSQL_PASSWORD}"
      # Recommended mysqldump flags for consistent dumps:
      DB01_MYSQL_SINGLE_TRANSACTION: "TRUE" # InnoDB-friendly consistent snapshots
      DB01_MYSQL_STORED_PROCEDURES: "TRUE"  # include routines
      DB01_MYSQL_EVENTS: "TRUE"             # include events

networks:
  nextcloud:
    name: nextcloud
    driver: bridge

volumes:
  nextcloud_mariadb:
  nextcloud_redis:
